Config = {}

QBCore = exports['qb-core']:GetCoreObject()

-- EMS Blood Draw --
Config.Registers = {
    ["Burgershot"] = {
        [1] = {
            location = vec3(0,0,0),
            orderPlaced = false,
            orderItems = {},
            orderPrice = 0,
        },
    }
}

Config.ImagePathing = "nui://lj-inventory/html/images/"

Config.Menus = {
    ["blackwoods"] = {
        titleLabel = "Burgershot Menu",
        description = "List Of All Burgershot Items",
        employeeDiscount = 20,
        govDiscount = 20,
        categories = {
            {label = "Appetizers", value = "apps"},
            {label = "Mains", value = "mains"},
            {label = "Drinks NA", value = "drinks"},
            {label = "Shots", value = "shots"},
            {label = "Cocktails", value = "cock"},
            {label = "Desserts", value = "dessert"},
            {label = "Specials", value = "specials"},
        },
        menuItems = {
            {
                itemname = "friedgreentomatoes",
                itemlabel = "Fried Green Tomatoes",
                itemcategory = "apps",
                combo = true,
                image = Config.ImagePathing,
                price = 6250,
                ingredients = {
                    {quantity = 5, item = "Mains"},
                    {quantity = 5, item = "Sides"},
                    {quantity = 5, item = "Desserts"},
                    {quantity = 5, item = "Drinks"},
                    {quantity = 1, item = "Toybox"},
                },
            },
        },
    },
    ["burgershot"] = {
        titleLabel = "Burgershot Menu",
        description = "List Of All Burgershot Items",
        employeeDiscount = 20,
        govDiscount = 20,
        categories = {
            {label = "Combos", value = "combo"},
            {label = "Main", value = "main"}, 
            {label = "Sides", value = "side"},
            {label = "Desserts", value = "dessert"},
            {label = "Drinks", value = "drink"},
            {label = "Extras", value = "extra"}
        },
        menuItems = {
            {
                itemname = "doublebarrelcombo",
                itemlabel = "Double Barrel Combo",
                itemcategory = "combo",
                combo = true,
                image = "https://www.in-n-out.com/ResourcePackages/INNOUT/content/images/menu/hamburger-meal.png?package=INNOUT&v=2023",
                price = 6250,
                ingredients = {
                    {quantity = 5, item = "Mains"},
                    {quantity = 5, item = "Sides"},
                    {quantity = 5, item = "Desserts"},
                    {quantity = 5, item = "Drinks"},
                    {quantity = 1, item = "Toybox"},
                },
            },
            {
                itemname = "meatloverscombo",
                itemlabel = "Meat Lovers Combo",
                itemcategory = "combo",
                combo = true,
                image = "https://popmenucloud.com/cdn-cgi/image/width%3D1200%2Cheight%3D1200%2Cfit%3Dscale-down%2Cformat%3Dauto%2Cquality%3D60/oeipabcd/48198147-38d1-4a2a-a7ce-f6eb44c439f0",
                price = 5750,
                ingredients = {
                    {quantity = 5, item = "Heartstoppers"},
                    {quantity = 5, item = "Bleeders"},
                    {quantity = 5, item = "Nuggets"},
                },
            },
            {
                itemname = "rabbitfoodcombo",
                itemlabel = "Rabbit Food Combo",
                itemcategory = "combo",
                combo = true,
                image = "https://paleogrubs.com/wp-content/uploads/2018/02/5a-salad-recipe-1024x1024.jpg",
                price = 4500,
                ingredients = {
                    {quantity = 5, item = "Shot Salad"},
                    {quantity = 5, item = "Meat-Free"},
                    {quantity = 5, item = "Drinks"},
                },
            },
            {
                itemname = "heartstopper",
                itemlabel = QBCore.Shared.Items["heartstopper"]["label"],
                itemcategory = "main",
                combo = false,
                image = Config.ImagePathing .. QBCore.Shared.Items["heartstopper"]["image"],
                price = 300,
                ingredients = {},
            },
            {
                itemname = "bleeder",
                itemlabel = QBCore.Shared.Items["bleeder"]["label"],
                itemcategory = "main",
                combo = false,
                image = Config.ImagePathing .. QBCore.Shared.Items["bleeder"]["image"],
                price = 300,
                ingredients = {},
            },
            {
                itemname = "torpedo", -- saucy shot
                itemlabel = QBCore.Shared.Items["torpedo"]["label"],
                itemcategory = "main",
                combo = false,
                image = Config.ImagePathing .. QBCore.Shared.Items["torpedo"]["image"],
                price = 300,
                ingredients = {},
            },
            {
                itemname = "moneyshot", -- double shot
                itemlabel = QBCore.Shared.Items["moneyshot"]["label"],
                itemcategory = "main",
                combo = false,
                image = Config.ImagePathing .. QBCore.Shared.Items["moneyshot"]["image"],
                price = 300,
                ingredients = {},
            },
            {
                itemname = "bs_backshot", -- backshot
                itemlabel = QBCore.Shared.Items["bs_backshot"]["label"],
                itemcategory = "main",
                combo = false,
                image = Config.ImagePathing .. QBCore.Shared.Items["bs_backshot"]["image"],
                price = 300,
                ingredients = {},
            },
            {
                itemname = "meatless", -- The Meat-Less
                itemlabel = QBCore.Shared.Items["meatless"]["label"],
                itemcategory = "main",
                combo = false,
                image = Config.ImagePathing .. QBCore.Shared.Items["meatless"]["image"],
                price = 300,
                ingredients = {},
            },
            {
                itemname = "cheesewrap", 
                itemlabel = QBCore.Shared.Items["cheesewrap"]["label"],
                itemcategory = "main",
                combo = false,
                image = Config.ImagePathing .. QBCore.Shared.Items["cheesewrap"]["image"],
                price = 300,
                ingredients = {},
            },
            {
                itemname = "bs_salad", 
                itemlabel = QBCore.Shared.Items["bs_salad"]["label"],
                itemcategory = "main",
                combo = false,
                image = Config.ImagePathing .. QBCore.Shared.Items["bs_salad"]["image"],
                price = 300,
                ingredients = {},
            },
            {
                itemname = "shotfries",
                itemlabel = QBCore.Shared.Items["shotfries"]["label"],
                itemcategory = "side",
                combo = false,
                image = Config.ImagePathing .. QBCore.Shared.Items["shotfries"]["image"],
                price = 250,
                ingredients = {},
            },
            {
                itemname = "shotrings",
                itemlabel = QBCore.Shared.Items["shotrings"]["label"],
                itemcategory = "side",
                combo = false,
                image = Config.ImagePathing .. QBCore.Shared.Items["shotrings"]["image"],
                price = 250,
                ingredients = {},
            },
            {
                itemname = "shotnuggets",
                itemlabel = QBCore.Shared.Items["shotnuggets"]["label"],
                itemcategory = "side",
                combo = false,
                image = Config.ImagePathing .. QBCore.Shared.Items["shotnuggets"]["image"],
                price = 250,
                ingredients = {},
            },
            {
                itemname = "bs_pickles",
                itemlabel = QBCore.Shared.Items["bs_pickles"]["label"],
                itemcategory = "side",
                combo = false,
                image = Config.ImagePathing .. QBCore.Shared.Items["bs_pickles"]["image"],
                price = 250,
                ingredients = {},
            },
            {
                itemname = "rimjob",
                itemlabel = QBCore.Shared.Items["rimjob"]["label"],
                itemcategory = "dessert",
                combo = false,
                image = Config.ImagePathing .. QBCore.Shared.Items["rimjob"]["image"],
                price = 250,
                ingredients = {},
            },
            {
                itemname = "creampie",
                itemlabel = QBCore.Shared.Items["creampie"]["label"],
                itemcategory = "dessert",
                combo = false,
                image = Config.ImagePathing .. QBCore.Shared.Items["creampie"]["image"],
                price = 250,
                ingredients = {},
            },
            {
                itemname = "bs_sundae",
                itemlabel = QBCore.Shared.Items["bs_sundae"]["label"],
                itemcategory = "dessert",
                combo = false,
                image = Config.ImagePathing .. QBCore.Shared.Items["bs_sundae"]["image"],
                price = 250,
                ingredients = {},
            },
            {
                itemname = "bs_cola",
                itemlabel = QBCore.Shared.Items["bs_cola"]["label"],
                itemcategory = "drink",
                combo = false,
                image = Config.ImagePathing .. QBCore.Shared.Items["bs_cola"]["image"],
                price = 300,
                ingredients = {},
            },
            {
                itemname = "bs_sprunk",
                itemlabel = QBCore.Shared.Items["bs_sprunk"]["label"],
                itemcategory = "drink",
                combo = false,
                image = Config.ImagePathing .. QBCore.Shared.Items["bs_sprunk"]["image"],
                price = 300,
                ingredients = {},
            },
            {
                itemname = "bs_orange",
                itemlabel = QBCore.Shared.Items["bs_orange"]["label"],
                itemcategory = "drink",
                combo = false,
                image = Config.ImagePathing .. QBCore.Shared.Items["bs_orange"]["image"],
                price = 300,
                ingredients = {},
            },
            {
                itemname = "bs_cherrysprunk",
                itemlabel = QBCore.Shared.Items["bs_cherrysprunk"]["label"],
                itemcategory = "drink",
                combo = false,
                image = Config.ImagePathing .. QBCore.Shared.Items["bs_cherrysprunk"]["image"],
                price = 300,
                ingredients = {},
            },
            {
                itemname = "bs_ultrawired",
                itemlabel = QBCore.Shared.Items["bs_ultrawired"]["label"],
                itemcategory = "drink",
                combo = false,
                image = Config.ImagePathing .. QBCore.Shared.Items["bs_ultrawired"]["image"],
                price = 300,
                ingredients = {},
            },
            {
                itemname = "bs-box",
                itemlabel = QBCore.Shared.Items["bs-box"]["label"],
                itemcategory = "extra",
                combo = false,
                image = Config.ImagePathing .. QBCore.Shared.Items["bs-box"]["image"],
                price = 1500,
                ingredients = {},
            },
        },
    }
}
  
--------------------